version: "3.9"

services:
  server:
    build:
      context: "./server"
      target: "development"
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://anon_chat:anon_chat@postgres:5432/anon_chat
      - REDIS_URL=redis://:anon_chat@redis:6379/0
    ports:
      - "3000:3000"
    networks:
      - server
    depends_on:
      - redis
      - postgres

  redis:
    image: bitnami/redis:7.0
    restart: always
    environment:
      - REDIS_PASSWORD=anon_chat
    ports:
      - "6379:6379"
    networks:
      - server
    volumes:
      - default:/bitnami/redis/data

  postgres:
    image: bitnami/postgresql:12.14.0
    restart: always
    environment:
      - POSTGRESQL_USERNAME=anon_chat
      - POSTGRESQL_PASSWORD=anon_chat
      - POSTGRESQL_DATABASE=anon_chat
    ports:
      - "5432:5432"
    networks:
      - server
    volumes:
      - default:/bitnami/postgresql

volumes:
  default:
    driver: local

networks:
  server:
    driver: bridge